spring:
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/back-ms-users-webflux_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password123}
  flyway:
    url: ${FLYWAY_URL:jdbc:postgresql://localhost:5432/back-ms-users-webflux_db}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password123}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.springframework.r2dbc: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true